### ISSUE TITLE
Lapotronic Chargepad does not always recognize the player

### ISSUE THREAD

**Issue by Thurion** [Myrathi/ChargePadsEx#4] opened 2013-06-04 13:00 UTC
When stepping on a lapotronic charge pad in SMP, it does not always start to charge. After relogging, it works right away. It looks like that traveling through dimensional doors always causes this issue (only in SMP)

Some of the used mods are IC² Build #314, ChargePads 2.7.0 Build 86, Dimensional Doors (R1.3.6RC1-71) and GraviSuite 1.9.2

**Comment by Myrathi** [comment] 2013-06-06 03:58
Is it just the Lap-pad or is it any pad?

Do you appear directly on the pad, from the dimdoor or are you walking onto it?

If relogging - as a client - fixed the issue, then I daresay it's not a ChP issue (as it's the player entity that's being refreshed, not the the pad).

**Comment by Thurion** [comment] 2013-06-11 20:02
You may be right. I noticed this issue on normal pressure plates as well lately. It looks like that this is a DimDoors problem.

**Comment by Myrathi** [comment] 2013-06-11 22:06
Something to bring up with them, then. Feel free to point them at this ticket when you report it.

I couldn't reproduce your issue in any other situation, though, so I'm going to close this. Thank you for the initial report, anyway.

**Closed as completed by Myrathi** 2013-06-11 22:06 UTC
Labels: v2.7.0.86 (1.5.2)
