### ISSUE TITLE
Cant load

### ISSUE THREAD

**Issue by vfukala** [Myrathi/ChargePadsEx#8] opened 2013-08-28 13:16 UTC
Minecraft cannot load.

I have: IC2 2.0.114
          Chargepads 2.8.0.93

When Minecraft is loading its write this:

An invalid crafting recipe was attempted to be added. This could happen due to a bug in IndustrialCraft 2 or an addon.

(Technical information: AdvRecipe, unknown type)
R: 1xitem.upgradeEmitterModule@1
O: null
T: null

**Comment by Myrathi** [comment] 2013-08-28 15:51
Duplicate of #7 - please search existing issues before posting new ones. Thanks.

**Closed as completed by Myrathi** 2013-08-28 15:51 UTC
Labels: duplicate
